### ISSUE TITLE
static libraries are included

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/aom-feedstock#7]
As of the pacakge `linux-64/aom-3.3.0-h9c3ff4c_0.tar.bz2`, it seems that static libraries are included
![image](https://user-images.githubusercontent.com/90008/155540465-66a8dd9b-e0ca-41f3-b7b4-9e66cf0a657f.png)

The source code for CMake makes no senses to me.

If you ask to build shared, then it builds static????
https://aomedia.googlesource.com/aom/+/refs/heads/main/CMakeLists.txt#275

**Comment by matthiasdiener** [comment]
Good catch :-). My guess is that BUILD_SHARED_LIBS indicates to *also* build shared libraries, not just the static ones. I think when that flag is enabled, all cmake targets will built shared libs by default, which is why it creates additional targets for the static versions of the libs. This is just speculation though.

**Comment by hmaarrfk** [comment]
I made a PR that address things. Thnaks for the quick comment.

**Comment by jakirkham** [comment]
Is this resolved with PR ( https://github.com/conda-forge/aom-feedstock/pull/8 ) now merged?

**Comment by matthiasdiener** [comment]
> Is this resolved with PR ( #8 ) now merged?

As far as I can see, yes.
